# -*- coding: utf-8 -*-
"""projeto-site-tenisipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DklbcJo64vLQP4Gdrl7JDjBNv24yfSMd
"""

print("ola, vamos nessa jornada juntos")

print("Seja nem vindo ao melhor site de tenis do Brasil")
nome = input("Para prosseguirmos, digite seu nome")
print("Ola" , nome)
idade = int(input("Agora digite sua idade"))
if idade >= 18:
  print("Seja bem vindo" , nome)
else:
  print("Apenas maiores de 18 anos podem realizar compras em nosso site")

print("Por qual tenis voce procura dentre estas opções abaixo")

print("1- tenis Nike- R$350")
print("2- temis Adidas- R$250")
print("3- tenis Zara- R$500")

escolha = input("\nDigite o numero que voçe quer")

if escolha == "1":
  print("\nVocê escolheu o tenis Nike, no valor de 350 reais")
elif escolha == "2":
  print("\nVocê escolheu o tenis Adidas, no valor de 250 reais")
elif escolha == "3":
  print("\nVocê escolheu o tenis Zara, no valor de 500 reais")

endereço = input(f"Digite seu endereço para entrega, {nome}")
print("A entrega sera realizada entre 2 a 4 dias uteis em", endereço)
print("OBS: pagamento realizado somente na entrega do produto")